version: "3"
services:
  es-2:
    image: elasticsearch:2.3.2
    container_name: es-2
    volumes:
      - ./elasticsearch/2.3.2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es-2-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9202:9200
      - 127.0.0.1:9302:9300

  es-5.2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: es-5.2
    volumes:
      - ./elasticsearch/5.2.2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es-5-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    restart: always

  es-5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: es-5
    volumes:
      - ./elasticsearch/5.6.3/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es-5-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9201:9200
      - 127.0.0.1:9301:9300

  pg-9.5:
    image: postgres:9.5
    container_name: pg-9.5
    volumes:
      - pg-9.5-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  pg-10:
    image: postgres:latest
    container_name: pg-10
    volumes:
      - pg-10-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /Users/psylone/development/web:/usr/share/nginx/html/web
      - /Users/psylone/development/projects/personal/psylone.github.io:/usr/share/nginx/html/psylone.github.io
    ports:
      - 80:80
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always

volumes:
  es-2-data:
  es-5-data:
  pg-9.5-data:
  pg-10-data:
